### PR TITLE
Access_token_issue_#28

### PR DESCRIPTION
**Pull request by filosssof**

### CODE REVIEW

**Comment by shai-benshimol** [comment]
core.js:1350 ERROR ReferenceError: response is not defined
    at HTMLScriptElement.eval [as __zone_symbol__ON_PROPERTYload] (angular4-social-login.umd.js:318)

**Comment by filosssof** [comment]
Access token issue. #28: Fixed issue with response undefinded 
This problem was fixed in the second commit.

**Comment by jaibatrik** [comment]
Will release to npm over the weekend. Could you please check if the access token can be obtained for Google provider as well (if you have some time :)?

**Comment by filipemendes1994** [comment]
@jaibatrik no, it could not be obtained for Google provider as well

**Comment by filipemendes1994** [comment]
@jaibatrik any news about this?

**Pull request merged**
